apiVersion: v1
kind: Secret
metadata:
  name: omnivideo-secrets
  namespace: omnivideo
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: changeme
  jwt-secret: changeme-jwt-secret
  redis-password: ""
